# This takes 6 hours
python train_model.py --checkpoint checkpoints/cifar10_residual_network/1 --output results/cifar10_residual_network --train_log recur_residual_network_width=8_depth=7_1.txt --model recur_residual_network --dataset cifar10 --val_period 20 --lr 0.1 --lr_schedule 100 150 175 --epochs 200 --problem classification --width 8 --depth 7 --save_json
python train_model.py --checkpoint checkpoints/cifar10_residual_network/1 --output results/cifar10_residual_network --train_log residual_network_width=8_depth=7_1.txt --model residual_network --dataset cifar10 --val_period 20 --lr 0.1 --lr_schedule 100 150 175 --epochs 200 --problem classification --width 8 --depth 7 --save_json
python train_model.py --checkpoint checkpoints/cifar10_residual_network/1 --output results/cifar10_residual_network --train_log recur_residual_network_width=8_depth=11_1.txt --model recur_residual_network --dataset cifar10 --val_period 20 --lr 0.1 --lr_schedule 100 150 175 --epochs 200 --problem classification --width 8 --depth 11 --save_json
python train_model.py --checkpoint checkpoints/cifar10_residual_network/1 --output results/cifar10_residual_network --train_log residual_network_width=8_depth=11_1.txt --model residual_network --dataset cifar10 --val_period 20 --lr 0.1 --lr_schedule 100 150 175 --epochs 200 --problem classification --width 8 --depth 11 --save_json
python train_model.py --checkpoint checkpoints/cifar10_residual_network/1 --output results/cifar10_residual_network --train_log recur_residual_network_width=8_depth=15_1.txt --model recur_residual_network --dataset cifar10 --val_period 20 --lr 0.1 --lr_schedule 100 150 175 --epochs 200 --problem classification --width 8 --depth 15 --save_json
python train_model.py --checkpoint checkpoints/cifar10_residual_network/1 --output results/cifar10_residual_network --train_log residual_network_width=8_depth=15_1.txt --model residual_network --dataset cifar10 --val_period 20 --lr 0.1 --lr_schedule 100 150 175 --epochs 200 --problem classification --width 8 --depth 15 --save_json
python train_model.py --checkpoint checkpoints/cifar10_residual_network/1 --output results/cifar10_residual_network --train_log recur_residual_network_width=8_depth=19_1.txt --model recur_residual_network --dataset cifar10 --val_period 20 --lr 0.01 --lr_schedule 100 150 175 --epochs 200 --problem classification --width 8 --depth 19 --save_json
python train_model.py --checkpoint checkpoints/cifar10_residual_network/1 --output results/cifar10_residual_network --train_log residual_network_width=8_depth=19_1.txt --model residual_network --dataset cifar10 --val_period 20 --lr 0.1 --lr_schedule 100 150 175 --epochs 200 --problem classification --width 8 --depth 19 --save_json

python train_model.py --checkpoint checkpoints/cifar10_residual_network/2 --output results/cifar10_residual_network --train_log recur_residual_network_width=8_depth=7_2.txt --model recur_residual_network --dataset cifar10 --val_period 20 --lr 0.1 --lr_schedule 100 150 175 --epochs 200 --problem classification --width 8 --depth 7 --save_json
python train_model.py --checkpoint checkpoints/cifar10_residual_network/2 --output results/cifar10_residual_network --train_log residual_network_width=8_depth=7_2.txt --model residual_network --dataset cifar10 --val_period 20 --lr 0.1 --lr_schedule 100 150 175 --epochs 200 --problem classification --width 8 --depth 7 --save_json
python train_model.py --checkpoint checkpoints/cifar10_residual_network/2 --output results/cifar10_residual_network --train_log recur_residual_network_width=8_depth=11_2.txt --model recur_residual_network --dataset cifar10 --val_period 20 --lr 0.1 --lr_schedule 100 150 175 --epochs 200 --problem classification --width 8 --depth 11 --save_json
python train_model.py --checkpoint checkpoints/cifar10_residual_network/2 --output results/cifar10_residual_network --train_log residual_network_width=8_depth=11_2.txt --model residual_network --dataset cifar10 --val_period 20 --lr 0.1 --lr_schedule 100 150 175 --epochs 200 --problem classification --width 8 --depth 11 --save_json
python train_model.py --checkpoint checkpoints/cifar10_residual_network/2 --output results/cifar10_residual_network --train_log recur_residual_network_width=8_depth=15_2.txt --model recur_residual_network --dataset cifar10 --val_period 20 --lr 0.1 --lr_schedule 100 150 175 --epochs 200 --problem classification --width 8 --depth 15 --save_json
python train_model.py --checkpoint checkpoints/cifar10_residual_network/2 --output results/cifar10_residual_network --train_log residual_network_width=8_depth=15_2.txt --model residual_network --dataset cifar10 --val_period 20 --lr 0.1 --lr_schedule 100 150 175 --epochs 200 --problem classification --width 8 --depth 15 --save_json
python train_model.py --checkpoint checkpoints/cifar10_residual_network/2 --output results/cifar10_residual_network --train_log recur_residual_network_width=8_depth=19_2.txt --model recur_residual_network --dataset cifar10 --val_period 20 --lr 0.01 --lr_schedule 100 150 175 --epochs 200 --problem classification --width 8 --depth 19 --save_json
python train_model.py --checkpoint checkpoints/cifar10_residual_network/2 --output results/cifar10_residual_network --train_log residual_network_width=8_depth=19_2.txt --model residual_network --dataset cifar10 --val_period 20 --lr 0.1 --lr_schedule 100 150 175 --epochs 200 --problem classification --width 8 --depth 19 --save_json

#python train_model.py --checkpoint checkpoints/cifar10_resnet_bn/1 --output results/cifar10_resnet_bn --train_log resnet18_1.txt --model resnet18 --dataset cifar10 --val_period 20 --lr 0.1 --lr_schedule 100 150 175 --epochs 200 --problem classification --save_json
#python train_model.py --checkpoint checkpoints/cifar10_resnet_bn/2 --output results/cifar10_resnet_bn --train_log resnet18_2.txt --model resnet18 --dataset cifar10 --val_period 20 --lr 0.1 --lr_schedule 100 150 175 --epochs 200 --problem classification --save_json
#python train_model.py --checkpoint checkpoints/cifar10_resnet_bn/3 --output results/cifar10_resnet_bn --train_log resnet18_3.txt --model resnet18 --dataset cifar10 --val_period 20 --lr 0.1 --lr_schedule 100 150 175 --epochs 200 --problem classification --save_json