# This takes 7 hrs

python train_model.py --checkpoint checkpoints/mazes_small_segment_check/1 --output results/mazes_small_segment --train_log residual_network_width=2_depth=8_1.txt --model residual_network_segment --dataset mazes_small --val_period 25 --lr 0.1 --lr_schedule 60 120 --epochs 150 --problem segment --save_json --save_period 50 --train_batch_size 50 --width 2 --depth 8
python train_model.py --checkpoint checkpoints/mazes_small_segment_check/1 --output results/mazes_small_segment --train_log residual_network_width=2_depth=12_1.txt --model residual_network_segment --dataset mazes_small --val_period 25 --lr 0.05 --lr_schedule 50 100 --epochs 150 --problem segment --save_json --save_period 50 --train_batch_size 50 --width 2 --depth 12
python train_model.py --checkpoint checkpoints/mazes_small_segment_check/1 --output results/mazes_small_segment --train_log residual_network_width=2_depth=16_1.txt --model residual_network_segment --dataset mazes_small --val_period 25 --lr 0.001 --lr_schedule 175 --epochs 200 --problem segment --save_json --save_period 50 --train_batch_size 50 --width 2 --depth 16
python train_model.py --checkpoint checkpoints/mazes_small_segment_check/1 --output results/mazes_small_segment --train_log residual_network_width=2_depth=20_1.txt --model residual_network_segment --dataset mazes_small --val_period 25 --lr 0.001 --lr_schedule 175 --epochs 200 --problem segment --save_json --save_period 50 --train_batch_size 50 --width 2 --depth 20
python train_model.py --checkpoint checkpoints/mazes_small_segment_check/1 --output results/mazes_small_segment --train_log residual_network_width=2_depth=24_1.txt --model residual_network_segment --dataset mazes_small --val_period 25 --lr 0.001 --lr_schedule 175 --epochs 200 --problem segment --save_json --save_period 50 --train_batch_size 50 --width 2 --depth 24
python train_model.py --checkpoint checkpoints/mazes_small_segment_check/1 --output results/mazes_small_segment --train_log residual_network_width=2_depth=28_1.txt --model residual_network_segment --dataset mazes_small --val_period 25 --lr 0.001 --lr_schedule 175 --epochs 200 --problem segment --save_json --save_period 50 --train_batch_size 50 --width 2 --depth 28
python train_model.py --checkpoint checkpoints/mazes_small_segment_check/1 --output results/mazes_small_segment --train_log residual_network_width=2_depth=36_1.txt --model residual_network_segment --dataset mazes_small --val_period 25 --lr 0.001 --lr_schedule 175 --epochs 200 --problem segment --save_json --save_period 50 --train_batch_size 50 --width 2 --depth 36
python train_model.py --checkpoint checkpoints/mazes_small_segment_check/1 --output results/mazes_small_segment --train_log residual_network_width=2_depth=44_1.txt --model residual_network_segment --dataset mazes_small --val_period 25 --lr 0.001 --lr_schedule 175 --epochs 200 --problem segment --save_json --save_period 50 --train_batch_size 50 --width 2 --depth 44
python train_model.py --checkpoint checkpoints/mazes_small_segment_check/1 --output results/mazes_small_segment --train_log recur_residual_network_width=2_depth=8_1.txt --model recur_residual_network_segment --dataset mazes_small --val_period 25 --lr 0.1 --lr_schedule 175 --epochs 200 --problem segment --save_json --save_period 50 --train_batch_size 50 --width 2 --depth 8
python train_model.py --checkpoint checkpoints/mazes_small_segment_check/1 --output results/mazes_small_segment --train_log recur_residual_network_width=2_depth=12_1.txt --model recur_residual_network_segment --dataset mazes_small --val_period 25 --lr 0.05 --lr_schedule 50 100 --epochs 150 --problem segment --save_json --save_period 50 --train_batch_size 50 --width 2 --depth 12
python train_model.py --checkpoint checkpoints/mazes_small_segment_check/1 --output results/mazes_small_segment --train_log recur_residual_network_width=2_depth=16_1.txt --model recur_residual_network_segment --dataset mazes_small --val_period 25 --lr 0.02 --lr_schedule 50 100 --epochs 150 --problem segment --save_json --save_period 50 --train_batch_size 50 --width 2 --depth 16
python train_model.py --checkpoint checkpoints/mazes_small_segment_check/1 --output results/mazes_small_segment --train_log recur_residual_network_width=2_depth=20_1.txt --model recur_residual_network_segment --dataset mazes_small --val_period 25 --lr 0.01 --lr_schedule 50 100 --epochs 150 --problem segment --save_json --save_period 50 --train_batch_size 50 --width 2 --depth 20
python train_model.py --checkpoint checkpoints/mazes_small_segment_check/1 --output results/mazes_small_segment --train_log recur_residual_network_width=2_depth=24_1.txt --model recur_residual_network_segment --dataset mazes_small --val_period 20 --lr 0.002 --lr_factor 0.5 --lr_schedule 60 120 --epochs 160 --problem segment --save_json --save_period 50 --train_batch_size 50 --width 2 --depth 24
python train_model.py --checkpoint checkpoints/mazes_small_segment_check/1 --output results/mazes_small_segment --train_log recur_residual_network_width=2_depth=28_1.txt --model recur_residual_network_segment --dataset mazes_small --val_period 20 --lr 0.002 --lr_factor 0.25 --lr_schedule 60 120 --epochs 160 --problem segment --save_json --save_period 50 --train_batch_size 50 --width 2 --depth 28
python train_model.py --checkpoint checkpoints/mazes_small_segment_check/1 --output results/mazes_small_segment --train_log recur_residual_network_width=2_depth=36_1.txt --model recur_residual_network_segment --dataset mazes_small --val_period 20 --lr 0.001 --lr_factor 0.25 --lr_schedule 40 100 --epochs 160 --problem segment --save_json --save_period 50 --train_batch_size 50 --width 2 --depth 36
python train_model.py --checkpoint checkpoints/mazes_small_segment_check/1 --output results/mazes_small_segment --train_log recur_residual_network_width=2_depth=44_1.txt --model recur_residual_network_segment --dataset mazes_small --val_period 20 --lr 0.001 --lr_factor 0.25 --lr_schedule 60 120 --epochs 160 --problem segment --save_json --save_period 50 --train_batch_size 50 --width 2 --depth 44

# -------------------------------------------------------------------------------------------------------------------

python train_model.py --checkpoint checkpoints/mazes_medium_segment_fixed_check/1 --output results/mazes_medium_segment_fixed --train_log residual_network_width=2_depth=8_1.txt --model residual_network_segment --dataset mazes_medium --val_period 20 --lr 0.1 --lr_schedule 60 120 --epochs 150 --problem segment --save_json --save_period 50 --train_batch_size 50 --width 2 --depth 8
python train_model.py --checkpoint checkpoints/mazes_medium_segment_fixed_check/1 --output results/mazes_medium_segment_fixed --train_log residual_network_width=2_depth=12_1.txt --model residual_network_segment --dataset mazes_medium --val_period 25 --lr 0.05 --lr_schedule 50 100 --epochs 150 --problem segment --save_json --save_period 50 --train_batch_size 50 --width 2 --depth 12
python train_model.py --checkpoint checkpoints/mazes_medium_segment_fixed_check/1 --output results/mazes_medium_segment_fixed --train_log residual_network_width=2_depth=16_1.txt --model residual_network_segment --dataset mazes_medium --val_period 25 --lr 0.001 --lr_schedule 175 --epochs 200 --problem segment --save_json --save_period 50 --train_batch_size 50 --width 2 --depth 16
python train_model.py --checkpoint checkpoints/mazes_medium_segment_fixed_check/1 --output results/mazes_medium_segment_fixed --train_log residual_network_width=2_depth=20_1.txt --model residual_network_segment --dataset mazes_medium --val_period 25 --lr 0.001 --lr_schedule 175 --epochs 200 --problem segment --save_json --save_period 50 --train_batch_size 50 --width 2 --depth 20
python train_model.py --checkpoint checkpoints/mazes_medium_segment_fixed_check/1 --output results/mazes_medium_segment_fixed --train_log residual_network_width=2_depth=24_1.txt --model residual_network_segment --dataset mazes_medium --val_period 25 --lr 0.001 --lr_schedule 175 --epochs 200 --problem segment --save_json --save_period 50 --train_batch_size 50 --width 2 --depth 24
python train_model.py --checkpoint checkpoints/mazes_medium_segment_fixed_check/1 --output results/mazes_medium_segment_fixed --train_log residual_network_width=2_depth=28_1.txt --model residual_network_segment --dataset mazes_medium --val_period 25 --lr 0.001 --lr_schedule 175 --epochs 200 --problem segment --save_json --save_period 50 --train_batch_size 50 --width 2 --depth 28
python train_model.py --checkpoint checkpoints/mazes_medium_segment_fixed_check/1 --output results/mazes_medium_segment_fixed --train_log residual_network_width=2_depth=36_1.txt --model residual_network_segment --dataset mazes_medium --val_period 25 --lr 0.001 --lr_schedule 175 --epochs 200 --problem segment --save_json --save_period 50 --train_batch_size 50 --width 2 --depth 36
python train_model.py --checkpoint checkpoints/mazes_medium_segment_fixed_check/1 --output results/mazes_medium_segment_fixed --train_log residual_network_width=2_depth=44_1.txt --model residual_network_segment --dataset mazes_medium --val_period 25 --lr 0.001 --lr_schedule 175 --epochs 200 --problem segment --save_json --save_period 50 --train_batch_size 50 --width 2 --depth 44
python train_model.py --checkpoint checkpoints/mazes_medium_segment_fixed_check/1 --output results/mazes_medium_segment_fixed --train_log recur_residual_network_width=2_depth=8_1.txt --model recur_residual_network_segment --dataset mazes_medium --val_period 25 --lr 0.1 --lr_schedule 175 --epochs 200 --problem segment --save_json --save_period 50 --train_batch_size 50 --width 2 --depth 8
python train_model.py --checkpoint checkpoints/mazes_medium_segment_fixed_check/1 --output results/mazes_medium_segment_fixed --train_log recur_residual_network_width=2_depth=12_1.txt --model recur_residual_network_segment --dataset mazes_medium --val_period 25 --lr 0.05 --lr_schedule 50 100 --epochs 150 --problem segment --save_json --save_period 50 --train_batch_size 50 --width 2 --depth 12
python train_model.py --checkpoint checkpoints/mazes_medium_segment_fixed_check/1 --output results/mazes_medium_segment_fixed --train_log recur_residual_network_width=2_depth=16_1.txt --model recur_residual_network_segment --dataset mazes_medium --val_period 25 --lr 0.05 --lr_schedule 50 100 --epochs 150 --problem segment --save_json --save_period 50 --train_batch_size 50 --width 2 --depth 16
python train_model.py --checkpoint checkpoints/mazes_medium_segment_fixed_check/1 --output results/mazes_medium_segment_fixed --train_log recur_residual_network_width=2_depth=20_1.txt --model recur_residual_network_segment --dataset mazes_medium --val_period 25 --lr 0.04 --lr_schedule 50 100 --epochs 150 --problem segment --save_json --save_period 50 --train_batch_size 50 --width 2 --depth 20
python train_model.py --checkpoint checkpoints/mazes_medium_segment_fixed_check/1 --output results/mazes_medium_segment_fixed --train_log recur_residual_network_width=2_depth=24_1.txt --model recur_residual_network_segment --dataset mazes_medium --val_period 20 --lr 0.008 --lr_factor 0.5 --lr_schedule 60 120 --epochs 160 --problem segment --save_json --save_period 50 --train_batch_size 50 --width 2 --depth 24
python train_model.py --checkpoint checkpoints/mazes_medium_segment_fixed_check/1 --output results/mazes_medium_segment_fixed --train_log recur_residual_network_width=2_depth=28_1.txt --model recur_residual_network_segment --dataset mazes_medium --val_period 20 --lr 0.006 --lr_factor 0.25 --lr_schedule 60 120 --epochs 160 --problem segment --save_json --save_period 50 --train_batch_size 50 --width 2 --depth 28
python train_model.py --checkpoint checkpoints/mazes_medium_segment_fixed_check/1 --output results/mazes_medium_segment_fixed --train_log recur_residual_network_width=2_depth=36_1.txt --model recur_residual_network_segment --dataset mazes_medium --val_period 20 --lr 0.006 --lr_factor 0.25 --lr_schedule 40 80 --epochs 120 --problem segment --save_json --save_period 50 --train_batch_size 50 --width 2 --depth 36
python train_model.py --checkpoint checkpoints/mazes_medium_segment_fixed_check/1 --output results/mazes_medium_segment_fixed --train_log recur_residual_network_width=2_depth=44_1.txt --model recur_residual_network_segment --dataset mazes_medium --val_period 20 --lr 0.004 --lr_factor 0.25 --lr_schedule 40 80 --epochs 120 --problem segment --save_json --save_period 50 --train_batch_size 50 --width 2 --depth 44
#----------------------------------

python train_model.py --checkpoint checkpoints/mazes_large_segment_check/1 --output results/mazes_large_segment --train_log residual_network_width=2_depth=8_1.txt --model residual_network_segment --dataset mazes_large --val_period 25 --lr 0.1 --lr_schedule 60 120 --epochs 160 --problem segment --save_json --save_period 50 --train_batch_size 50 --width 2 --depth 8
python train_model.py --checkpoint checkpoints/mazes_large_segment_check/1 --output results/mazes_large_segment --train_log residual_network_width=2_depth=12_1.txt --model residual_network_segment --dataset mazes_large --val_period 25 --lr 0.05 --lr_schedule 50 100 --epochs 150 --problem segment --save_json --save_period 50 --train_batch_size 50 --width 2 --depth 12
python train_model.py --checkpoint checkpoints/mazes_large_segment_check/1 --output results/mazes_large_segment --train_log residual_network_width=2_depth=16_1.txt --model residual_network_segment --dataset mazes_large --val_period 25 --lr 0.005 --lr_schedule 175 --epochs 200 --problem segment --save_json --save_period 50 --train_batch_size 50 --width 2 --depth 16
python train_model.py --checkpoint checkpoints/mazes_large_segment_check/1 --output results/mazes_large_segment --train_log residual_network_width=2_depth=20_1.txt --model residual_network_segment --dataset mazes_large --val_period 25 --lr 0.002 --lr_schedule 175 --epochs 200 --problem segment --save_json --save_period 50 --train_batch_size 50 --width 2 --depth 20
python train_model.py --checkpoint checkpoints/mazes_large_segment_check/1 --output results/mazes_large_segment --train_log residual_network_width=2_depth=24_1.txt --model residual_network_segment --dataset mazes_large --val_period 25 --lr 0.002 --lr_schedule 175 --epochs 200 --problem segment --save_json --save_period 50 --train_batch_size 50 --width 2 --depth 24
python train_model.py --checkpoint checkpoints/mazes_large_segment_check/1 --output results/mazes_large_segment --train_log residual_network_width=2_depth=28_1.txt --model residual_network_segment --dataset mazes_large --val_period 25 --lr 0.002 --lr_schedule 175 --epochs 200 --problem segment --save_json --save_period 50 --train_batch_size 50 --width 2 --depth 28
python train_model.py --checkpoint checkpoints/mazes_large_segment_check/1 --output results/mazes_large_segment --train_log residual_network_width=2_depth=36_1.txt --model residual_network_segment --dataset mazes_large --val_period 25 --lr 0.002 --lr_schedule 175 --epochs 200 --problem segment --save_json --save_period 50 --train_batch_size 50 --width 2 --depth 36
python train_model.py --checkpoint checkpoints/mazes_large_segment_check/1 --output results/mazes_large_segment --train_log residual_network_width=2_depth=44_1.txt --model residual_network_segment --dataset mazes_large --val_period 25 --lr 0.002 --lr_schedule 175 --epochs 200 --problem segment --save_json --save_period 50 --train_batch_size 50 --width 2 --depth 44
python train_model.py --checkpoint checkpoints/mazes_large_segment_check/1 --output results/mazes_large_segment --train_log recur_residual_network_width=2_depth=8_1.txt --model recur_residual_network_segment --dataset mazes_large --val_period 25 --lr 0.1 --lr_schedule 175 --epochs 200 --problem segment --save_json --save_period 50 --train_batch_size 50 --width 2 --depth 8
python train_model.py --checkpoint checkpoints/mazes_large_segment_check/1 --output results/mazes_large_segment --train_log recur_residual_network_width=2_depth=12_1.txt --model recur_residual_network_segment --dataset mazes_large --val_period 25 --lr 0.05 --lr_schedule 50 100 --epochs 150 --problem segment --save_json --save_period 50 --train_batch_size 50 --width 2 --depth 12
python train_model.py --checkpoint checkpoints/mazes_large_segment_check/1 --output results/mazes_large_segment --train_log recur_residual_network_width=2_depth=16_1.txt --model recur_residual_network_segment --dataset mazes_large --val_period 25 --lr 0.04 --lr_schedule 75 125 --epochs 150 --problem segment --save_json --save_period 50 --train_batch_size 50 --width 2 --depth 16
python train_model.py --checkpoint checkpoints/mazes_large_segment_check/1 --output results/mazes_large_segment --train_log recur_residual_network_width=2_depth=20_1.txt --model recur_residual_network_segment --dataset mazes_large --val_period 25 --lr 0.02 --lr_schedule 75 125 --epochs 150 --problem segment --save_json --save_period 50 --train_batch_size 50 --width 2 --depth 20
python train_model.py --checkpoint checkpoints/mazes_large_segment_check/1 --output results/mazes_large_segment --train_log recur_residual_network_width=2_depth=24_1.txt --model recur_residual_network_segment --dataset mazes_large --val_period 20 --lr 0.01 --lr_factor 0.1 --lr_schedule 80 140 --epochs 180 --problem segment --save_json --save_period 50 --train_batch_size 50 --width 2 --depth 24
python train_model.py --checkpoint checkpoints/mazes_large_segment_check/1 --output results/mazes_large_segment --train_log recur_residual_network_width=2_depth=28_1.txt --model recur_residual_network_segment --dataset mazes_large --val_period 20 --lr 0.006 --lr_factor 0.25 --lr_schedule 80 140 --epochs 180 --problem segment --save_json --save_period 50 --train_batch_size 50 --width 2 --depth 28
python train_model.py --checkpoint checkpoints/mazes_large_segment_check/1 --output results/mazes_large_segment --train_log recur_residual_network_width=2_depth=36_1.txt --model recur_residual_network_segment --dataset mazes_large --val_period 20 --lr 0.004 --lr_factor 0.25 --lr_schedule 80 140 --epochs 200 --problem segment --save_json --save_period 50 --train_batch_size 50 --width 2 --depth 36
python train_model.py --checkpoint checkpoints/mazes_large_segment_check/1 --output results/mazes_large_segment --train_log recur_residual_network_width=2_depth=44_1.txt --model recur_residual_network_segment --dataset mazes_large --val_period 20 --lr 0.006 --lr_factor 0.25 --lr_schedule 60 120 --epochs 180 --problem segment --save_json --save_period 50 --train_batch_size 50 --width 2 --depth 44
